# Generated by Django 2.2.6 on 2019-11-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee id')),
                ('f_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('wage', models.IntegerField(verbose_name='Wage')),
                ('contact', models.IntegerField(verbose_name='Contact')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('typE', models.CharField(max_length=20, verbose_name='Type')),
                ('company', models.CharField(max_length=30, verbose_name='Company')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Supplier ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact_no', models.IntegerField(verbose_name='Contact number')),
                ('s_name', models.CharField(max_length=20, verbose_name='Supplier Name')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Record ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_price', models.IntegerField(verbose_name='Total Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Supplier'),
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('log_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Log Number')),
                ('sign_out', models.TimeField(verbose_name='Sign Out')),
                ('date', models.DateField(verbose_name='Date')),
                ('sign_in', models.TimeField(verbose_name='Sign in')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Products')),
            ],
        ),
    ]
