# Generated by Django 2.2.6 on 2019-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Product ID'),
        ),
    ]
