# Generated by Django 2.2.6 on 2019-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20191103_2321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expirydetails',
            unique_together={('p_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliercat',
            unique_together={('category', 's_id')},
        ),
    ]
