# Generated by Django 2.2.6 on 2019-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20191106_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirydetails',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
        migrations.AlterUniqueTogether(
            name='expirydetails',
            unique_together={('date', 'p_id')},
        ),
    ]
