# Generated by Django 2.2.6 on 2019-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20191108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirydetails',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
    ]
