# Generated by Django 2.2.6 on 2019-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20191108_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirydetails',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
