# Generated by Django 2.2.6 on 2019-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20191108_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
    ]
