# Generated by Django 2.2.6 on 2019-11-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20191108_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
    ]
