# Generated by Django 2.2.6 on 2019-11-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20191108_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='sign_in',
            field=models.CharField(max_length=5, verbose_name='Sign in'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='sign_out',
            field=models.CharField(max_length=5, verbose_name='Sign Out'),
        ),
    ]
