# Generated by Django 2.2.6 on 2019-11-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20191109_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Employee'),
        ),
    ]
