# Generated by Django 2.2.6 on 2019-11-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='p_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.CharField(max_length=30, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.CharField(max_length=30, verbose_name='Total Price'),
        ),
    ]
