# Generated by Django 2.2.6 on 2019-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_auto_20191109_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(verbose_name='Total Price'),
        ),
    ]
