# Generated by Django 2.2.6 on 2019-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_auto_20191109_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='log_num',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
