# Generated by Django 2.2.6 on 2019-11-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_auto_20191109_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='p_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Shop.Products'),
        ),
    ]
