# Generated by Django 2.2.7 on 2019-11-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_auto_20191110_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='sign_out',
            field=models.CharField(max_length=5, null=True, verbose_name='Sign Out'),
        ),
    ]
