# Generated by Django 2.1 on 2019-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_auto_20191119_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='p_id',
            field=models.IntegerField(verbose_name='Product ID'),
        ),
    ]
